"""Generate decode controls from the CSV; no third-party dependencies."""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FORMATS = ['N', 'R', 'I', 'S', 'B', 'U', 'J', 'SH']
UNITS = ['NONE', 'ALU', 'LOAD', 'STORE', 'BRANCH', 'JUMP', 'FENCE', 'SYSTEM', 'MULDIV']
ALUS = ['PASS', 'ADD', 'SUB', 'SLL', 'LT', 'LTU', 'XOR', 'SRL', 'SRA', 'OR', 'AND', 'EQ', 'NE', 'GE', 'GEU', 'MUL', 'MULH', 'MULHSU', 'MULHU', 'DIV', 'DIVU', 'REM', 'REMU']
# Packed MSB-first; keep in sync with the explicit ctrl_t declarations below.
FIELDS = [('legal',1), ('op',6), ('fmt',3), ('unit',4), ('alu',5),
          ('rs1',1), ('rs2',1), ('write',1), ('size',2), ('unsigned',1),
          ('trap',2), ('serial',1)]
CTRL_W = sum(w for _,w in FIELDS)

def pack(values, fields=FIELDS):
    result = 0
    for name, width in fields:
        value = values[name]
        if not 0 <= value < 1 << width:
            raise ValueError((name, value))
        result = (result << width) | value
    return result

def controls(row, op):
    values = {key:int(row[key]) for key in ['rs1','rs2','write','size','unsigned','trap','serial']}
    values.update(legal=1, op=op, fmt=FORMATS.index(row['format']),
                  unit=UNITS.index(row['unit']), alu=ALUS.index(row['alu']))
    return pack(values)

def merge(cubes):
    """Exact cube combination only; never expand into unspecified encodings."""
    current, primes = set(cubes), set()
    while current:
        used, following = set(), set()
        for mask, value in current:
            bits = mask
            while bits:
                bit = bits & -bits
                other = (mask, value ^ bit)
                if other in current:
                    used.add((mask,value)); used.add(other)
                    following.add((mask ^ bit, value & ~bit))
                bits ^= bit
        primes.update(current - used)
        current = following
    # Remove cubes wholly covered by a more general cube.
    return sorted(c for c in primes if not any(
        c != d and (d[0] & c[0]) == d[0] and (c[1] & d[0]) == d[1]
        for d in primes))

def main():
    rows = list(csv.DictReader((ROOT/'spec/instructions.csv').open(newline='')))
    for i, r in enumerate(rows,1):
        r['mask_i'], r['match_i'] = int(r['mask'],16), int(r['match'],16)
        assert r['match_i'] & ~r['mask_i'] == 0
        r['control'] = controls(r,i)
    for i,a in enumerate(rows):
        for b in rows[i+1:]:
            shared = a['mask_i'] & b['mask_i']
            assert (a['match_i'] & shared) != (b['match_i'] & shared), (a['name'],b['name'])
    dest = ROOT/'rtl/generated'
    dest.mkdir(parents=True,exist_ok=True)
    header = '// Generated by tools/generate.py. Edit spec/instructions.csv instead.\n'
    pkg = header + 'package decode_pkg;\n'
    for label, items in [('FMT',FORMATS),('UNIT',UNITS),('ALU',ALUS)]:
        pkg += '\n'.join(f'  localparam int {label}_{name} = {i};' for i,name in enumerate(items))+'\n'
    pkg += '\n'.join(f"  localparam int OP_{r['name']} = {i};" for i,r in enumerate(rows,1))+'\n'
    pkg += '''  typedef struct packed {
    logic legal;
    logic [5:0] op;
    logic [2:0] fmt;
    logic [3:0] unit_id;
    logic [4:0] alu;
    logic uses_rs1, uses_rs2, writes_rd;
    logic [1:0] mem_size;
    logic mem_unsigned;
    logic [1:0] trap;
    logic serializing;
  } ctrl_t;
  typedef struct packed {
    logic valid, illegal;
    ctrl_t ctrl;
    logic [4:0] rd, rs1, rs2;
    logic [31:0] imm;
    logic [11:0] fence;
  } decode_t;
  localparam int CTRL_W = $bits(ctrl_t);
  localparam int DECODE_W = $bits(decode_t);
  function automatic decode_t payload(input logic [31:0] insn,
                                      input logic valid, input ctrl_t ctrl);
    decode_t d;
    d = '0;
    if (valid) begin
      d.valid = 1;
      d.illegal = !ctrl.legal;
      if (ctrl.legal) begin
        d.ctrl = ctrl;
        d.rd = ctrl.writes_rd ? insn[11:7] : 5'b0;
        d.rs1 = ctrl.uses_rs1 ? insn[19:15] : 5'b0;
        d.rs2 = ctrl.uses_rs2 ? insn[24:20] : 5'b0;
        d.ctrl.writes_rd = ctrl.writes_rd && (insn[11:7] != 0);
        case (ctrl.fmt)
          FMT_I: d.imm = {{20{insn[31]}}, insn[31:20]};
          FMT_S: d.imm = {{20{insn[31]}}, insn[31:25], insn[11:7]};
          FMT_B: d.imm = {{19{insn[31]}}, insn[31], insn[7], insn[30:25], insn[11:8], 1'b0};
          FMT_U: d.imm = {insn[31:12], 12'b0};
          FMT_J: d.imm = {{11{insn[31]}}, insn[31], insn[19:12], insn[20], insn[30:21], 1'b0};
          FMT_SH: d.imm = {27'b0, insn[24:20]};
          default: d.imm = 0;
        endcase
        if (ctrl.unit_id == UNIT_FENCE) d.fence = insn[31:20];
      end
    end
    return d;
  endfunction
endpackage
'''
    (dest/'decode_pkg.sv').write_text(pkg)
    def start(name):
        return header+f'''module {name} #(parameter bit ENABLE_M = 0)
  (input logic [31:0] insn, output decode_pkg::ctrl_t ctrl);
  import decode_pkg::*;
'''
    direct = start('control_direct') + '  always_comb begin\n    ctrl = \'0;\n    casez (insn)\n'
    for r in rows:
        pattern = ''.join(str((r['match_i']>>b)&1) if (r['mask_i']>>b)&1 else '?' for b in range(31,-1,-1))
        enable = 'ENABLE_M' if r['extension']=='M' else "1'b1"
        direct += f"      32'b{pattern}: if ({enable}) ctrl = {CTRL_W}'h{r['control']:x}; // {r['name']}\n"
    direct += '      default: ctrl = \'0;\n    endcase\n  end\nendmodule\n'
    (dest/'control_direct.sv').write_text(direct)
    exact = start('control_pla') + f'  logic [{len(rows)-1}:0] hit;\n'
    for i,r in enumerate(rows):
        en = 'ENABLE_M' if r['extension']=='M' else "1'b1"
        exact += f"  assign hit[{i}] = {en} && ((insn & 32'h{r['mask']}) == 32'h{r['match']});\n"
    for bit in range(CTRL_W):
        terms = [f'hit[{i}]' for i,r in enumerate(rows) if (r['control']>>bit)&1]
        exact += f"  assign ctrl[{bit}] = "+(' | '.join(terms) or "1'b0")+';\n'
    (dest/'control_pla.sv').write_text(exact+'endmodule\n')
    # Minimize each output independently, preserving separate extension enables,
    # then share identical product terms across output equations.
    equations, unique = [], {}
    for bit in range(CTRL_W):
        terms = []
        for extension in ['I','M']:
            for mask,value in merge([(r['mask_i'],r['match_i']) for r in rows if r['extension']==extension and (r['control']>>bit)&1]):
                key = (extension,mask,value)
                if key not in unique: unique[key] = len(unique)
                terms.append(unique[key])
        equations.append(terms)
    minimized = start('control_shared')+f'  logic [{len(unique)-1}:0] product;\n'
    for (ext,mask,value),idx in unique.items():
        en = 'ENABLE_M' if ext=='M' else "1'b1"
        minimized += f"  assign product[{idx}] = {en} && ((insn & 32'h{mask:08x}) == 32'h{value:08x});\n"
    for bit,terms in enumerate(equations):
        minimized += f"  assign ctrl[{bit}] = "+(' | '.join(f'product[{t}]' for t in terms) or "1'b0")+';\n'
    (dest/'control_shared.sv').write_text(minimized+'endmodule\n')
    stats = {'instructions':len(rows),'rv32i_instructions':sum(r['extension']=='I' for r in rows),
             'control_bits':CTRL_W,'exact_product_terms':len(rows),
             'shared_product_terms':len(unique),
             'shared_or_connections':sum(map(len,equations)),
             'note':'Exact cube merging, not globally minimal logic; physical synthesis may map all variants similarly.'}
    (dest/'generation_stats.json').write_text(json.dumps(stats,indent=2)+'\n')
    print(json.dumps(stats))

if __name__ == '__main__': main()
